name: React Native Build and Deploy

on:
  push:
    branches:
      - master  # Adjust this to the branches you want to trigger the build on

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.1' # Match with your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17.0.11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: '30.0.3'

      - name: Build Android APK
        run: |
          ./gradlew assembleRelease

      - name: Upload APK (Optional)
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk

  build-ios:
    name: Build iOS App
    runs-on: macos-latest
    needs: build-android

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.1' # Match with your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Set up CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios
          pod install

      - name: Build iOS App
        run: |
          xcodebuild -workspace ios/YourApp.xcworkspace \
            -scheme YourApp \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/YourApp.xcarchive archive

      - name: Upload iOS Archive (Optional)
        uses: actions/upload-artifact@v2
        with:
          name: app-release.xcarchive
          path: ios/build/YourApp.xcarchive
