name: Node.js CI with Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4

      # Setup Node.js environment based on the matrix version
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies
      - run: npm ci

      # Build the project if a build script is present
      - run: npm run build --if-present

      # Run tests if a test script is present
      - name: Run tests if script is present
        run: |
          if grep -q '"test":' package.json; then
            npm test
          else
            echo "No test script found, skipping tests."
          fi

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t mentor-matrix .

      # Log in to Docker Hub (ensure secrets are added in GitHub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Tag and push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker tag mentor-matrix ${{ secrets.DOCKER_USERNAME }}/mentor-matrix:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mentor-matrix:latest
